/**
 * The perk icons, checked against the data rather than against a list.
 *
 * The point of this file is the first test: the recipe table is vendored from
 * upstream and re-generated by `npm run db`, so a ninth profession can arrive
 * without anyone touching this repo. The badge would render the placeholder and
 * nobody would notice. This fails instead, and names the perk.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { hasPerkIcon, perkIcon, perkTint, PERKS_WITH_ICONS } from '../src/lib/craft-icons.ts';
import { hideout } from '../src/lib/server/recipes.ts';

/** Every perk any recipe actually gates on. */
const referenced = [
	...new Set(hideout.flatMap((r) => Object.keys(r.perks ?? {})))
].sort();

test('every profession the recipes reference has an icon of its own', () => {
	const missing = referenced.filter((p) => !hasPerkIcon(p));
	assert.deepEqual(missing, [], `no icon for: ${missing.join(', ')} — add one to $lib/craft-icons`);
});

test('no icon is drawn for a profession that does not exist', () => {
	// the other direction: a perk renamed upstream leaves a glyph nothing uses,
	// and a stale mark is how a set drifts out of the language it was drawn in
	const orphans = PERKS_WITH_ICONS.filter((p) => !referenced.includes(p));
	assert.deepEqual(orphans, [], `unused perk icons: ${orphans.join(', ')}`);
});

test('an unknown perk gets a placeholder, not a hole in the row', () => {
	const fallback = perkIcon('sorcery');
	assert.match(fallback, /^<svg/);
	assert.equal(hasPerkIcon('sorcery'), false);
});

test('the marks are inert svg in the site language', () => {
	for (const p of PERKS_WITH_ICONS) {
		const svg = perkIcon(p);
		assert.match(svg, /viewBox="0 0 24 24"/, `${p} must share the 24×24 box`);
		// currentColor is what lets the badge's own colour and hover reach the mark
		assert.match(svg, /stroke="currentColor"/, `${p} must inherit its colour`);
		assert.match(svg, /aria-hidden="true"/, `${p} is decoration beside its own label`);
		assert.doesNotMatch(svg, /<script|on[a-z]+=/i, `${p} must be inert`);
	}
});

test('every profession draws something different', () => {
	const drawn = PERKS_WITH_ICONS.map(perkIcon);
	assert.equal(new Set(drawn).size, drawn.length, 'two professions share a mark');
});

test('every profession has a tint, and it is a palette name not a colour', () => {
	// A literal would freeze one skin into the module. `palette.css` declares all
	// eight three times over — dark, and twice for light, once per way the theme
	// can be chosen — and a var() is what lets those reach the mark.
	for (const p of PERKS_WITH_ICONS) {
		assert.equal(perkTint(p), `var(--perk-${p})`, `${p} needs a palette tint`);
	}
	// unknown perk: the body colour, never a wrong hue
	assert.equal(perkTint('sorcery'), 'currentColor');
});

test('palette.css declares a tint for every profession, in every skin', () => {
	// The three blocks are dark, prefers-color-scheme: light, and the
	// [data-theme='light'] override the toggle stamps — a hue missing from any
	// one of them renders as an inherited colour in that skin only, which is
	// exactly the bug nobody notices until they flip the theme.
	const css = readFileSync(new URL('../src/lib/styles/palette.css', import.meta.url), 'utf8');
	for (const p of PERKS_WITH_ICONS) {
		const declared = css.split(`--perk-${p}:`).length - 1;
		assert.equal(declared, 3, `--perk-${p} declared ${declared} times, expected 3`);
	}
});
