/**
 * The stat marks, checked against the data rather than against a list.
 *
 * Same rule as tests/craft-icons.test.ts, and here it matters more: the stat
 * dictionary is regenerated by `npm run db` straight out of EXBO's translation
 * keys, so a patch that adds a stat lands 161 → 162 without anyone touching this
 * repo. Every table that renders it would quietly show the placeholder. These
 * fail instead, and name the slug.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import {
	hasStatIcon,
	statConcept,
	statGroup,
	statGroupLabel,
	statGroupOrder,
	statIcon,
	statTint,
	STAT_CONCEPT,
	STAT_CONCEPTS,
	STAT_FAMILIES,
	STAT_FAMILY,
	STAT_GROUP_KEYS
} from '../src/lib/stat-icons.ts';
import db from '../src/lib/data/items.json' with { type: 'json' };

const slugs = Object.keys(db.stats).sort();

test('every stat in the database has a mark', () => {
	const missing = slugs.filter((s) => !hasStatIcon(s));
	assert.deepEqual(missing, [], `no mark for: ${missing.join(', ')} — map it in $lib/stat-icons`);
});

test('no mark is mapped for a stat that does not exist', () => {
	// the other direction: a slug renamed upstream leaves a mapping nothing can
	// reach, and stale entries are how a set drifts away from the data
	const orphans = Object.keys(STAT_CONCEPT).filter((s) => !(s in db.stats));
	assert.deepEqual(orphans, [], `mapped but not in the database: ${orphans.join(', ')}`);
});

test('every concept drawn is one some stat actually uses', () => {
	const used = new Set(Object.values(STAT_CONCEPT));
	const unused = STAT_CONCEPTS.filter((c) => !used.has(c));
	assert.deepEqual(unused, [], `marks nothing renders: ${unused.join(', ')}`);
});

test('no stat maps to a concept nobody drew', () => {
	const undrawn = [...new Set(Object.values(STAT_CONCEPT))].filter(
		(c) => !STAT_CONCEPTS.includes(c)
	);
	assert.deepEqual(undrawn, [], `mapped to a missing mark: ${undrawn.join(', ')}`);
});

test('an unknown stat gets a placeholder, not a hole in the row', () => {
	assert.match(statIcon('art_telekinesis'), /^<svg/);
	assert.equal(hasStatIcon('art_telekinesis'), false);
	assert.equal(statConcept('art_telekinesis'), null);
});

test('the marks are inert svg in the site language', () => {
	for (const slug of slugs) {
		const svg = statIcon(slug);
		assert.match(svg, /viewBox="0 0 24 24"/, `${slug} must share the 24×24 box`);
		// currentColor is what lets a good/bad row tint its own mark
		assert.match(svg, /stroke="currentColor"/, `${slug} must inherit its colour`);
		assert.match(svg, /aria-hidden="true"/, `${slug} is decoration beside its own label`);
		assert.doesNotMatch(svg, /<script|on[a-z]+=/i, `${slug} must be inert`);
	}
});

test('every concept draws something different', () => {
	const first = (c: string) => Object.keys(STAT_CONCEPT).find((s) => STAT_CONCEPT[s] === c)!;
	const drawn = STAT_CONCEPTS.map((c) => statIcon(first(c)));
	assert.equal(new Set(drawn).size, drawn.length, 'two concepts share a mark');
});

/**
 * The stats that sit on one screen together, and which therefore have to be told
 * apart rather than merely recognised as a family.
 *
 * Read off the data: these are the pairs where both slugs are carried by the same
 * items in quantity, so they are adjacent rows on an entity page or adjacent
 * columns on a compatibility table. A shared mark there is not a shortcut, it is
 * two different numbers wearing the same badge.
 */
const MUST_DIFFER: [string, string][] = [
	['durability', 'max_durability'],
	['art_durability', 'art_max_durability'],
	['plate_durability', 'plate_armor'],
	['mag_reload_time', 'mag_reload_time_tactical'],
	['mag_full_reload_time', 'mag_single_round_reload_time'],
	['mag_clip_size', 'mag_additive_clip_size'],
	['spread', 'hip_spread'],
	['upg_spread', 'upg_hip_spread'],
	['recoil', 'horizontal_recoil'],
	['upg_recoil', 'upg_recoil_gain'],
	['upg_recoil', 'upg_horizontal_recoil'],
	['ammo_piercing', 'ammo_plate_penetrating'],
	['ammo_piercing', 'ammo_stopping_power'],
	['ammo_bleeding', 'ammo_combustion'],
	['upg_reload_modifier', 'mag_reload_time'],
	['art_stamina_bonus', 'art_stamina_regeneration_bonus'],
	['art_speed_modifier', 'art_sprint_speed_modifier'],
	['art_artefakt_heal', 'art_regeneration_bonus'],
	['art_health_bonus', 'art_heal_efficiency'],
	['art_thermal_protection', 'art_frost_protection'],
	['art_thermal_protection', 'art_explosion_dmg_factor'],
	['art_radiation_protection', 'art_biological_protection'],
	['art_radiation_protection', 'art_radiation_accumulation'],
	['art_bleeding_protection', 'art_bleeding_accumulation'],
	['art_bullet_dmg_factor', 'art_tear_dmg_factor'],
	['frag_explosion_strength', 'frag_explosion_size'],
	['frag_explosion_activation_time', 'frag_lifetime'],
	['detector_active_scan_radius', 'detector_passive_scan_radius'],
	['melee_dmg_max_common', 'melee_dmg_max_strong'],
	['med_duration', 'med_cooldown']
];

test('stats a player sees side by side do not share a mark', () => {
	for (const [a, b] of MUST_DIFFER) {
		assert.ok(a in db.stats, `${a} is no longer in the database — fix this list`);
		assert.ok(b in db.stats, `${b} is no longer in the database — fix this list`);
		assert.notEqual(
			statConcept(a),
			statConcept(b),
			`${a} and ${b} appear together and both draw ${statConcept(a)}`
		);
	}
});

/**
 * The composition rule from the module header, asserted rather than described: a
 * hazard's protection is the hazard behind a shield, and a reaction is the
 * hazard inside a ring. The silhouette is what carries the family at 14px, so a
 * guard that lost its shield is a real regression and an invisible one.
 */
test('protection marks are shields and reactions are rings', () => {
	const guards = Object.keys(STAT_CONCEPT).filter((s) => STAT_CONCEPT[s].endsWith('Guard'));
	assert.ok(guards.length >= 13, 'the hazard vocabulary shrank — check the mapping');
	for (const slug of guards) {
		assert.match(statIcon(slug), /M12 2\.4 20\.4 5\.5/, `${slug} must be drawn behind the shield`);
	}

	const reactions = Object.keys(STAT_CONCEPT).filter((s) => STAT_CONCEPT[s].endsWith('Reaction'));
	assert.equal(reactions.length, 4, 'there are four anomaly reactions in the data');
	for (const slug of reactions) {
		assert.match(statIcon(slug), /A8\.6 8\.6 0 1 1/, `${slug} must be drawn inside the ring`);
	}
});

test('an accumulation and its protection are the same hazard, drawn differently', () => {
	// the pairing is the whole point of `shielded`: strip the suffix and the two
	// must name the same hazard, or the shield is sitting over the wrong mark
	const pairs: [string, string][] = [
		['art_radiation_accumulation', 'art_radiation_protection'],
		['art_biological_accumulation', 'art_biological_protection'],
		['art_psycho_accumulation', 'art_psycho_protection'],
		['art_thermal_accumulation', 'art_thermal_protection'],
		['art_frost_accumulation', 'art_frost_protection'],
		['art_bleeding_accumulation', 'art_bleeding_protection'],
		['art_combustion_accumulation', 'art_burn_dmg_factor']
	];
	for (const [hazard, guard] of pairs) {
		assert.equal(
			`${statConcept(hazard)}Guard`,
			statConcept(guard),
			`${guard} does not shield ${statConcept(hazard)}`
		);
	}
});

/*
 * ── THE TINTS ─────────────────────────────────────────────────────────────────
 *
 * Two things can rot independently here: a concept can arrive without a family,
 * and a family can name a token palette.css does not declare. Either one ships a
 * mark whose `color` resolves to nothing, which on the dark skin is invisible —
 * so both are checked, and the second is checked against the stylesheet itself
 * rather than against a copy of its names.
 */
const PALETTE = readFileSync(new URL('../src/lib/styles/palette.css', import.meta.url), 'utf8');

test('every concept belongs to a group, and so has a tint', () => {
	const missing = STAT_CONCEPTS.filter((c) => !(c in STAT_FAMILY));
	assert.deepEqual(missing, [], `not in any STAT_GROUPS entry: ${missing.join(', ')}`);
});

test('no group lists a concept nobody draws', () => {
	const orphans = Object.keys(STAT_FAMILY).filter((c) => !STAT_CONCEPTS.includes(c));
	assert.deepEqual(orphans, [], `grouped but never drawn: ${orphans.join(', ')}`);
});

test('every concept is in exactly one group', () => {
	// STAT_FAMILY is built by flatMap, so a concept listed twice would silently
	// take whichever group came last — and sort into that one block only
	const counts = new Map<string, number>();
	for (const key of STAT_GROUP_KEYS) {
		for (const slug of Object.keys(STAT_CONCEPT)) {
			if (statGroup(slug) === key) counts.set(STAT_CONCEPT[slug], key.length);
		}
	}
	const groupsOf = (concept: string) =>
		STAT_GROUP_KEYS.filter((k) =>
			Object.keys(STAT_CONCEPT).some((s) => STAT_CONCEPT[s] === concept && statGroup(s) === k)
		);
	const duplicated = STAT_CONCEPTS.filter((c) => groupsOf(c).length > 1);
	assert.deepEqual(duplicated, [], `in more than one group: ${duplicated.join(', ')}`);
});

test('a hazard guard and reaction inherit their hazard tint by construction', () => {
	// this is the rule HAZARD_FAMILY exists to make unrepresentable rather than
	// merely tested, so the test is here to catch the derivation breaking
	let checked = 0;
	for (const concept of STAT_CONCEPTS) {
		const stem = concept.replace(/(Guard|Reaction)$/, '');
		// `bullet` is the one stem with no bare mark of its own — nothing in the
		// data is bullet damage of type bullet, only resistance to it — so there is
		// nothing to compare it against. It is pinned separately below.
		if (stem === concept || !(stem in STAT_FAMILY)) continue;
		assert.equal(
			STAT_FAMILY[concept],
			STAT_FAMILY[stem],
			`${concept} does not take ${stem}'s tint`
		);
		checked++;
	}
	assert.ok(checked >= 14, `only ${checked} composed marks checked — the derivation may be gone`);
	assert.equal(statTint('art_bullet_dmg_factor'), 'var(--stat-trauma)');
});

test('every family has a token in the palette, on both skins', () => {
	for (const family of STAT_FAMILIES) {
		const declarations = PALETTE.split(`--stat-${family}:`).length - 1;
		assert.ok(declarations >= 1, `--stat-${family} is not declared in palette.css`);
		// `vital` is the one that references --accent, which both skins already
		// re-declare, so it is correctly declared exactly once
		if (family !== 'vital') {
			assert.equal(
				declarations,
				3,
				`--stat-${family} must be declared for :root and both light selectors, found ${declarations}`
			);
		}
	}
});

test('the palette declares no stat token no family claims', () => {
	const declared = [...new Set([...PALETTE.matchAll(/--stat-([a-z]+):/g)].map((m) => m[1]))];
	const extra = declared.filter((f) => !STAT_FAMILIES.includes(f));
	assert.deepEqual(extra, [], `palette.css declares unused stat tints: ${extra.join(', ')}`);
});

test('a tint is always a var(), never a literal colour', () => {
	// baked hex would break the theme toggle, and would put the dark skin's hues
	// on the light one
	for (const slug of slugs) {
		assert.match(statTint(slug), /^var\(--[a-z-]+\)$/, `${slug} must resolve through a token`);
	}
	assert.equal(statTint('art_telekinesis'), 'var(--text-faint)');
});

test('the marks themselves carry no colour — the tint is applied outside them', () => {
	// `currentColor` is the whole contract: it is what lets a call site set the
	// family hue, and what lets EstimatePanel deliberately override it with --warn
	for (const slug of slugs) {
		assert.doesNotMatch(statIcon(slug), /#[0-9a-f]{3,8}|var\(--/i, `${slug} hardcodes a colour`);
	}
});

/**
 * The families a player sees together must not be one colour.
 *
 * Same argument as MUST_DIFFER above, one level up: on a suit's effects table the
 * hue is what separates a radiation row from a frost one before you read either,
 * so these pairs earning the same tint would waste the channel.
 */
test('hazards that share a page do not share a tint', () => {
	const pairs: [string, string][] = [
		['art_radiation_protection', 'art_thermal_protection'],
		['art_radiation_protection', 'art_frost_protection'],
		['art_thermal_protection', 'art_frost_protection'],
		['art_psycho_protection', 'art_electra_dmg_factor'],
		['art_bleeding_protection', 'art_burn_dmg_factor'],
		['art_bullet_dmg_factor', 'art_explosion_dmg_factor'],
		['art_speed_modifier', 'art_stopping_protection'],
		['weight', 'upg_recoil'],
		['durability', 'dmg_direct']
	];
	for (const [a, b] of pairs) {
		assert.notEqual(statTint(a), statTint(b), `${a} and ${b} both tint ${statTint(a)}`);
	}
});

test('an accumulation and its protection share a tint — they are one subject', () => {
	// the mirror of the shape rule: the shield says which direction, the hue says
	// which hazard, and those two jobs must not both land on the shape
	const pairs: [string, string][] = [
		['art_radiation_accumulation', 'art_radiation_protection'],
		['art_frost_accumulation', 'art_frost_protection'],
		['art_bleeding_accumulation', 'art_bleeding_protection'],
		['art_thermal_accumulation', 'art_thermal_protection'],
		['art_combustion_accumulation', 'art_burn_dmg_factor'],
		['dmg_electroshock', 'art_electra_dmg_factor'],
		['dmg_tear', 'art_tear_dmg_factor']
	];
	for (const [hazard, guard] of pairs) {
		assert.equal(statTint(hazard), statTint(guard), `${hazard} and ${guard} disagree on hue`);
	}
});

/*
 * ── THE GROUPS ────────────────────────────────────────────────────────────────
 *
 * The groups decide reading order, and the whole reason they exist is that stats
 * a player compares should be adjacent. So the test is written as adjacency: for
 * each set below, the members must come out as one unbroken run.
 */
const MUST_BE_ADJACENT: [string, string[]][] = [
	['the ammunition cycle', ['mag_clip_size', 'mag_reload_time', 'mag_reload_time_tactical', 'rate_of_fire']],
	['where the shots go', ['spread', 'hip_spread', 'recoil', 'horizontal_recoil']],
	['getting on target', ['aim_switch', 'draw_time', 'upg_reload_modifier']],
	['what a suit stops', ['art_radiation_protection', 'art_thermal_protection', 'art_bullet_dmg_factor']],
	['what it does to you', ['art_radiation_accumulation', 'art_psycho_accumulation', 'art_frost_accumulation']],
	['how worn it is', ['durability', 'max_durability', 'plate_durability']],
	['a melee swing', ['melee_dmg_min_common', 'melee_dmg_max_strong', 'melee_reach_common']]
];

test('stats a player compares come out adjacent', () => {
	const all = slugs.filter(hasStatIcon);
	for (const [what, members] of MUST_BE_ADJACENT) {
		for (const m of members) assert.ok(m in db.stats, `${m} is gone from the database`);
		const orders = [...new Set(members.map(statGroupOrder))];
		assert.equal(
			orders.length,
			1,
			`${what}: ${members.map((m) => `${m}=${statGroup(m)}`).join(' ')} are not one group`
		);
		// and nothing outside the set may sort between them
		const between = all.filter(
			(s) => statGroupOrder(s) === orders[0] && !members.includes(s)
		);
		for (const s of between) {
			assert.equal(
				statGroup(s),
				statGroup(members[0]),
				`${s} sorts inside ${what} but is not part of it`
			);
		}
	}
});

test('the group order is total and unknown stats sort last', () => {
	for (const slug of slugs) {
		const order = statGroupOrder(slug);
		assert.ok(order >= 0 && order < STAT_GROUP_KEYS.length, `${slug} sorts outside the groups`);
		assert.ok(statGroup(slug), `${slug} has no group`);
		assert.ok(statGroupLabel(slug), `${slug} has no group label`);
	}
	assert.equal(statGroupOrder('art_telekinesis'), STAT_GROUP_KEYS.length);
	assert.equal(statGroup('art_telekinesis'), null);
	assert.equal(statGroupLabel('art_telekinesis'), null);
});

test('a group is one tint, except the three that are per-hazard', () => {
	// resistance, hazard and reaction each hold several hazards on purpose — every
	// other group must be one colour, or the block reads as several
	const perHazard = ['resistance', 'hazard', 'reaction'];
	for (const key of STAT_GROUP_KEYS) {
		if (perHazard.includes(key)) continue;
		const tints = new Set(slugs.filter((s) => statGroup(s) === key).map(statTint));
		assert.ok(tints.size <= 1, `group ${key} mixes tints: ${[...tints].join(', ')}`);
	}
});
