/**
 * Which gear is assembled from parts, and which of it is therefore bound.
 *
 * Reads `assembly.json`, generated by `scripts/build-assembly.ts` and committed.
 * The generator does the fragile half — joining "FN SCAR SSR Part" to `qj26k`
 * across a name, because upstream records no id link between them — so that the
 * matching happens once, in a reviewable diff, instead of on every boot.
 *
 * WHY THE AUCTION TAB NEEDS THIS
 *
 * `status` cannot answer whether a thing can be listed. All 338 weapons in the
 * catalogue carry `PERSONAL_ON_USE`, as do all 137 suits and all 280
 * attachments — it is a category-level fact ("weapons bind on use"), not a
 * per-item one. So `isAuctionable(status)` says yes to every weapon in the game,
 * including the assembled ones, which arrive personal and can never reach the
 * auction.
 *
 * This is the one signal in the data that separates them: FN SCAR SSR is
 * assembled from parts, FN Five-seveN has no parts at all.
 *
 * WHY IT IS ASSEMBLY AND NOT THE PARTS' OWN STATUS
 *
 * The first cut of this only bound gear built from a bind-on-pickup part, which
 * left 14 of the 39 assembled items auctionable. Scorpion EVO III was the one
 * that showed it up: its four parts are all `NON_DROP`, which means "kept on
 * death" and not "untradeable" — every artefact carries it — yet the assembled
 * SMG is personal in game all the same. No catalogue field predicts that, so the
 * rule is now assembly itself. `boundOnAssembly` is consequently true for all 39
 * groups; it stays a field so this stays one decision in one place. See
 * scripts/build-assembly.ts for the split that motivated the change.
 */
import assembly from '../data/assembly.json' with { type: 'json' };

interface AssemblyGroup {
	gear: string;
	gearName: string;
	via: string;
	parts: string[];
	boundOnAssembly: boolean;
}

const groups = (assembly as { groups: AssemblyGroup[] }).groups;

const byGear = new Map<string, AssemblyGroup>(groups.map((g) => [g.gear, g]));

/**
 * part id → the gear it builds. A list, not a single value: a part could in
 * principle serve two builds, and silently keeping the last one would be the
 * kind of bug that only shows up as a missing section on one page.
 */
const byPart = new Map<string, string[]>();
for (const g of groups) {
	for (const part of g.parts) {
		const owners = byPart.get(part);
		if (owners) owners.push(g.gear);
		else byPart.set(part, [g.gear]);
	}
}

/**
 * True when this gear is assembled from parts, which means every copy of it is
 * personal and none can be listed. Reads the generated flag rather than assuming
 * "assembled ⇒ bound" at the call site, so the rule has one home.
 */
export function boundOnAssembly(id: string): boolean {
	return byGear.get(id)?.boundOnAssembly ?? false;
}

/** The parts that build this gear, if it is assembled at all. */
export function partsFor(id: string): string[] {
	return byGear.get(id)?.parts ?? [];
}

export function isAssembled(id: string): boolean {
	return byGear.has(id);
}

/** The gear this part builds — the same link read from the other end. */
export function assemblesInto(id: string): string[] {
	return byPart.get(id) ?? [];
}

/**
 * Whether this item has anything to say about assembly, from either side. What
 * the Crafting tab gates on: that tab answers "how do I get one", and being
 * gathered in numbered parts is one of the answers.
 */
export function hasAssembly(id: string): boolean {
	return byGear.has(id) || byPart.has(id);
}
